# Generated by Django 6.0.7 on 2026-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_amenity_listing_floor_listing_has_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
