# Generated by Django 6.0.7 on 2026-07-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_area_listing_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/'),
        ),
    ]
