# Generated by Django 6.0.7 on 2026-08-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
    ]
