# Generated by Django 6.0.7 on 2026-08-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_created_at_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_demo',
            field=models.BooleanField(default=False, help_text="Bu e'lon namuna/test uchunmi? Ha bo'lsa, u katalogda emas, faqat bosh sahifadagi 'Namuna' bo'limida ko'rinadi."),
        ),
    ]
