# Generated by Django 6.0.7 on 2026-08-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_panorama',
            field=models.BooleanField(default=True, help_text="Rasm haqiqiy 360° panoramami? Frontend tomonidan rasm o'lcham nisbati (2:1) asosida avtomatik aniqlanadi."),
        ),
    ]
