# Generated by Django 6.0.7 on 2026-08-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_room_is_panorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False, help_text="E'lon admin tomonidan tasdiqlanganmi? Tasdiqlanmagan e'lonlar faqat o'z egasiga ko'rinadi, jamoatchilikka chiqmaydi."),
        ),
    ]
